set(IVE_LINK_LIBS
  ${MPP_PATH}/out/lib/libss_bnr.a
  ${MPP_PATH}/out/lib/libss_ir_auto.a
  ${MPP_PATH}/out/lib/libss_upvqe.a
  ${MPP_PATH}/out/lib/libvqe_talkv2.a
  ${MPP_PATH}/out/lib/libss_acs.a
  ${MPP_PATH}/out/lib/libsns_os05a10_2l_slave.a
  ${MPP_PATH}/out/lib/libss_ae.a
  ${MPP_PATH}/out/lib/libss_isp.a
  ${MPP_PATH}/out/lib/libss_ldci.a
  ${MPP_PATH}/out/lib/libaac_sbr_dec.a
  ${MPP_PATH}/out/lib/libvqe_agc.a
  ${MPP_PATH}/out/lib/libsns_os08a20.a
  ${MPP_PATH}/out/lib/libss_mau.a
  ${MPP_PATH}/out/lib/libvqe_res.a
  ${MPP_PATH}/out/lib/libvqe_record.a
  ${MPP_PATH}/out/lib/libss_voice_engine.a
  ${MPP_PATH}/out/lib/libss_drc.a
  ${MPP_PATH}/out/lib/libsns_imx347_slave.a
  ${MPP_PATH}/out/lib/libss_md.a
  ${MPP_PATH}/out/lib/libss_dnvqe.a
  ${MPP_PATH}/out/lib/libsns_os08b10.a
  ${MPP_PATH}/out/lib/libsns_os04a10.a
  ${MPP_PATH}/out/lib/libsns_imx485.a
  ${MPP_PATH}/out/lib/libss_dpu_match.a
  ${MPP_PATH}/out/lib/libss_hdmi.a
  ${MPP_PATH}/out/lib/libss_extend_stats.a
  ${MPP_PATH}/out/lib/libss_awb.a
  ${MPP_PATH}/out/lib/libaac_sbr_enc.a
  ${MPP_PATH}/out/lib/libss_dsp.a
  ${MPP_PATH}/out/lib/libvqe_eq.a
  ${MPP_PATH}/out/lib/libss_dpu_rect.a
  ${MPP_PATH}/out/lib/libot_isp.a
  ${MPP_PATH}/out/lib/libvqe_anr.a
  ${MPP_PATH}/out/lib/libss_ive.a
  ${MPP_PATH}/out/lib/libaac_enc.a
  ${MPP_PATH}/out/lib/libsecurec.a
  ${MPP_PATH}/out/lib/libss_dehaze.a
  ${MPP_PATH}/out/lib/libss_crb.a
  ${MPP_PATH}/out/lib/libvqe_hpf.a
  ${MPP_PATH}/out/lib/libaac_dec.a
  ${MPP_PATH}/out/lib/libss_calcflicker.a
  ${MPP_PATH}/out/lib/libvqe_aec.a
  ${MPP_PATH}/out/lib/libvqe_wnr.a
  ${MPP_PATH}/out/lib/libaac_comm.a
  ${MPP_PATH}/out/lib/libss_mpi.a
)
